version: 2.1

executors:
  cimg/base:
    docker:
      - image: cimg/base:stable

jobs:
  ios-ci:
    executor: cimg/base
    steps:
      - checkout
      - run: echo "iOS"
  android-ci:
    executor: cimg/base
    steps:
      - checkout
      - run: echo "Android"

workflows:
  ios-workflow:
    jobs:
      - ios-ci
  android-workflow:
    jobs:
      - android-ci
