version: 2.1

jobs:
  ios-ci:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "iOS"
  android-ci:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Android"

workflows:
  ios-workflow:
    jobs:
      - ios-ci
  android-workflow:
    jobs:
      - android-ci
