version: 2.1

executors:
  cimg-base:
    docker:
      - image: cimg/base:stable

parameters:
  build-android:
    type: boolean
    default: false
  build-ios:
    type: boolean
    default: false

jobs:
  ios-ci:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "iOS"
  android-ci:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "Android"
  dummy:
    executor: cimg-base
    steps:
      - checkout
      - run: echo "<< pipeline.parameters.build-ios >>"
      - run: echo "<< pipeline.parameters.build-android >>" 

workflows:
  ios-workflow:
    when: << pipeline.parameters.build-ios >>
    jobs:
      - ios-ci
  android-workflow:
    when: << pipeline.parameters.build-android >>
    jobs:
      - android-ci
  dummy:
    jobs:
      - dummy
